// Generated by CoffeeScript 1.7.1
(function(WIN, DOC) {
  var $, CLICK, Fancy, elBody, entry;
  $ = WIN["$"];
  elBody = $("body");
  CLICK = "click";
  Fancy = (function() {
    var easeHide, easeShow, elMask, fancyStyles, htmlContent, htmlMask, isHasMask, mask, maskStyles, publicStyles, transitionValue;

    htmlMask = "<div class='wallet-mask'></div>";

    htmlContent = ["<div class='wallet-fancy'>", "<em>X</em>", "</div>"];

    transitionValue = "all .3s ease";

    publicStyles = {
      position: "absolute",
      webkitTransition: transitionValue,
      transition: transitionValue,
      opacity: 0,
      display: "none"
    };

    maskStyles = {
      left: 0,
      top: 0,
      width: "100%",
      background: "rgba(0, 0, 0, .6)",
      zIndex: 10
    };

    $.extend(maskStyles, publicStyles);

    fancyStyles = {
      zIndex: 20,
      width: "80%",
      left: "50%",
      marginLeft: "-40%",
      top: "100px",
      background: "rgba(0, 0, 0, .6)",
      paddingTop: "20px"
    };

    $.extend(fancyStyles, publicStyles);

    easeShow = function(el, time) {
      if (time == null) {
        time = 100;
      }
      el.show();
      return setTimeout(function() {
        return el.css("opacity", 1);
      }, time);
    };

    easeHide = function(el, time) {
      if (time == null) {
        time = 100;
      }
      el.css("opacity", 0);
      return setTimeout(function() {
        return el.hide();
      }, 200);
    };

    elMask = null;

    isHasMask = false;

    mask = {
      init: function(config) {
        elMask = $(htmlMask);
        $.extend(maskStyles, config.maskStyles || {});
        elMask.css(maskStyles);
        elMask.height($(WIN).height());
        return elBody.append(elMask);
      },
      show: function() {
        return easeShow(elMask);
      },
      hide: function() {
        return easeHide(elMask, 200);
      }
    };

    function Fancy(config) {
      this.config = config != null ? config : {};
      this.content = this.config.content || "";
      this.elFancy = null;
    }

    Fancy.prototype.init = function() {
      var config, elClose, elFancy;
      config = this.config;
      if (!isHasMask) {
        mask.init(config);
      }
      isHasMask = true;
      htmlContent.splice(1, 0, this.content);
      this.elFancy = elFancy = $(htmlContent.join(""));
      $.extend(fancyStyles, config.fancyStyles || {});
      elFancy.css(fancyStyles);
      elBody.append(elFancy);
      this.elClose = elClose = $("em", elFancy);
      elClose.on(CLICK, (function(_this) {
        return function() {
          return _this.hide();
        };
      })(this));
      return this;
    };

    Fancy.prototype.show = function() {
      var elFancy;
      elFancy = this.elFancy;
      mask.show();
      easeShow(elFancy, 200);
      return this;
    };

    Fancy.prototype.hide = function() {
      var elFancy;
      elFancy = this.elFancy;
      mask.hide();
      return easeHide(elFancy);
    };

    return Fancy;

  })();
  entry = function(config) {
    return (new Fancy(config)).init();
  };
  if (typeof define === "function") {
    return define("wallet/fancy", function(require, exports, module) {
      return entry;
    });
  } else {
    return WIN["Fancy"] = entry;
  }
})(window, document);
